### ISSUE TITLE
Site is slow and users have problems logging in

### ISSUE THREAD

**Issue by wesblair** [JWDeveloper/JWManagement#274] opened 2018-10-25 15:28 UTC
After the update was made to the dash board the program has become slower. Many participants are having trouble getting into the program. Most of yesterday no one on our project could sign in, it just kept loading.

**Comment by MarvinZeising** [comment] 2018-10-26 07:19
Thanks for the issue.
It's a duplicate of #271, though.

**Closed by MarvinZeising** 2018-10-26 07:19 UTC
